Plot_RC('/home/michael/simulation/tb_PA_Cascode_ccg/spectre/config/psf',...
    'VG1', 'VG4', 'PA_Cascode_CG');

Plot_RC('/home/michael/simulation/tb_PA_Cascode_cin/spectre/config/psf',...
    'VI1', 'VI4', 'PA_Cascode_CIN');

Plot_RC('/home/michael/simulation/tb_PA_Cascode_cout/spectre/config/psf',...
    'VV0', 'VV3', 'PA_Cascode_COUT');
